version: '3.8'

services:
  # 1. PostgreSQL Database Service
  postgres:
    image: postgres:18-alpine
    restart: always
    environment:
      # PLEASE CHANGE THESE VALUES TO SECURE AND RANDOM ONES WHEN DEPLOYING TO AWS
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      # Can be opened for testing only, not safe to expose externally in production.
      - "5432:5432"

  # 2. NestJS Backend Service
  backend:
    build:
      context: ./ip-lookup-backend # The folder where Dockerfile is located
      dockerfile: Dockerfile.backend
    restart: always
    ports:
      # Backend port (3002) will be mapped to port 8080 externally
      - "8080:3002" 
    env_file:
      - ./ip-lookup-backend/.env
    depends_on:
      - postgres # Ensures that Postgres starts first
    networks:
      - ip_lookup_network

  # 3. Next.js Frontend Service
  frontend:
    build:
      context: ./ip-lookup-frontend # The folder where Dockerfile is located
      dockerfile: Dockerfile.frontend
    restart: always
    ports:
      # Frontend port will be mapped to port 80 externally (The main port the user will see)
      - "80:3000" 
    # The frontend needs to start after the backend to be able to access the API
    depends_on:
      - backend
    networks:
      - ip_lookup_network

# Volume for data persistence
volumes:
  postgres_data:

# Common Network
networks:
  ip_lookup_network:
    driver: bridge